### ISSUE TITLE
Broken compilation with LLVM 8.0.1

### ISSUE THREAD

**Issue by pkubaj** [OpenXRay/xray-16#499]
**Describe the bug**
I can't compile with LLVM 8.0.1:
/wrkdirs/usr/ports/games/openxray/work/xray-16-510/Externals/ode/ode/src/quickstep.cpp:428:9: error: no member named 'random_shuffle' in namespace 'std'
                        std::random_shuffle     (order,order+m);
                        ~~~~~^                                                                            
1 error generated.  

Note that std::random_shuffle was removed in C++17, but OpenXRay uses C++17. Either downgrade to C++14 or stop using std::random_shuffle.

**To Reproduce**
Try to compile with LLVM 8.0.1.

**Expected behavior**
The software should compile successfully.

**Desktop (please complete the following information):**
 - OS: FreeBSD 12.1-RC2
 - OpenXRay build version 510
