### PR TITLE
Fix for clang compilation

### LINKED ISSUE #289: [Linux] Clang build issues
Fatal error while building at Linux Ubuntu 18.04
CLang ver 6.0 used
There's console output:
$ CC=clang-6.0 CXX=clang++-6.0 CFLAGS="-march=native" CXXFLAGS="-march=native" cmake ..
-- The C compiler identification is Clang 6.0.0
-- The CXX compiler identification is Clang 6.0.0
-- Check for working C compiler: /usr/bin/clang-6.0
-- Check for working C compiler: /usr/bin/clang-6.0 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/clang++-6.0
-- Check for working CXX compiler: /usr/bin/clang++-6.0 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- cotire 1.8.0 loaded.
CMake build Release, CFLAGS=-march=native, CXXFLAGS=-march=native -fpermissive --std=c++17 -Wno-attributes -pipe -Wl,--no-undefined -fvisibility=hidden
-- Found GLEW: /usr/include  
-- Found FreeImage: /usr/include, /usr/lib/x86_64-linux-gnu/libfreeimage.so
-- Found LockFile: /usr/include, /usr/lib/x86_64-linux-gnu/liblockfile.so
-- Found OpenAL: /usr/lib/x86_64-linux-gnu/libopenal.so  
-- Found Crypto++: /usr/include/crypto++, /usr/lib/x86_64-linux-gnu/libcryptopp.so
-- Found PugiXML: /usr/lib/x86_64-linux-gnu/libpugixml.so  
-- PugiXML include = /usr/include
-- PugiXML library = /usr/lib/x86_64-linux-gnu/libpugixml.so
-- theora found: includes in /usr/include, library in /usr/lib/x86_64-linux-gnu/libtheora.so;/usr/lib/x86_64-linux-gnu/libogg.so;/usr/lib/x86_64-linux-gnu/libvorbis.so
-- Found Ogg: /usr/lib/x86_64-linux-gnu/libogg.so  
-- Found SDL: /usr/lib/x86_64-linux-gnu/libSDL2.so (found version "2.0.8") 
-- Found LZO: /usr/lib/x86_64-linux-gnu/liblzo2.so  
-- Found JPEG: /usr/lib/x86_64-linux-gnu/libjpeg.so  
-- Found Intel TBB, includes /usr/include, /usr/lib/x86_64-linux-gnu/libtbb.so;/usr/lib/x86_64-linux-gnu/libtbbmalloc.so;/usr/lib/x86_64-linux-gnu/libtbbmalloc_proxy.so
-- The ASM compiler identification is Clang
-- Found assembler: /usr/bin/clang-6.0
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Found readline: /usr/lib/x86_64-linux-gnu/libreadline.so  
-- Found Curses: /usr/lib/x86_64-linux-gnu/libcurses.so  
DASM_FLAGS: -D FPU -D HFABI -D P64 -D JIT -D FFI -D SSE2 -D VER=
DASM_ARCH: x86
Build shared lib
adding  ./src/GameSpy to GameSpy
adding  ./src/GameSpy/common to GameSpy
adding  ./src/GameSpy/gcdkey to GameSpy
adding  ./src/GameSpy/ghttp to GameSpy
adding  ./src/GameSpy/GP to GameSpy
adding  ./src/GameSpy/gstats to GameSpy
adding  ./src/GameSpy/gt2 to GameSpy
adding  ./src/GameSpy/natneg to GameSpy
adding  ./src/GameSpy/pt to GameSpy
adding  ./src/GameSpy/qr2 to GameSpy
adding  ./src/GameSpy/sake to GameSpy
adding  ./src/GameSpy/sc to GameSpy
adding  ./src/GameSpy/serverbrowsing to GameSpy
adding  ./src/GameSpy/webservices to GameSpy
adding  . to OPCODE
adding  ode/src to ODE
adding  include/ode to ODE
adding  contrib/msvc7/ode_default to ODE
adding  . to xrLCUtil
-- CXX target xrLCUtil cotired.
adding  src to xrQSlim
adding  . to xrMiscMath
-- CXX target xrMiscMath cotired.
adding  . to xrRender_GL
adding  ../xrRender to xrRender_GL
adding  ../xrRender/blenders to xrRender_GL
adding  ../xrRenderGL to xrRender_GL
adding  ../xrRenderGL/MSAA to xrRender_GL
adding  ../xrRenderGL/GL Rain to xrRender_GL
adding  ../../Include/xrRender to xrRender_GL
-- CXX target xrRender_GL cotired.
adding  . to xr_3da
adding  . to xrAICore
adding  Components to xrAICore
adding  Navigation to xrAICore
adding  Navigation/PatrolPath to xrAICore
adding  Navigation/PathManagers to xrAICore
-- CXX target xrAICore cotired.
path /home/lonesimba/Desktop/stalker/xray-16/src/xrUICore
adding  . to xrCDB
-- CXX target xrCDB cotired.
adding  . to xrCore
adding  Animation to xrCore
adding  Compression to xrCore
adding  Containers to xrCore
adding  Crypto to xrCore
adding  Math to xrCore
adding  Media to xrCore
adding  PostProcess to xrCore
adding  Text to xrCore
adding  Threading to xrCore
adding  XML to xrCore
adding  ../xrCommon to xrCore
commit: cf1329d6759723a5840b58b00a7660ccb16b1f94
branch: xd_dev
-- CXX target xrCore cotired.
adding  . to xrEngine
adding  StringTable to xrEngine
-- CXX target xrEngine cotired.
adding  . to xrGame
adding  ai to xrGame
adding  ai/crow to xrGame
adding  ai/monsters to xrGame
adding  ai/monsters/basemonster to xrGame
adding  ai/monsters/bloodsucker to xrGame
adding  ai/monsters/boar to xrGame
adding  ai/monsters/burer to xrGame
adding  ai/monsters/cat to xrGame
adding  ai/monsters/chimera to xrGame
adding  ai/monsters/controller to xrGame
adding  ai/monsters/dog to xrGame
adding  ai/monsters/flesh to xrGame
adding  ai/monsters/fracture to xrGame
adding  ai/monsters/group_states to xrGame
adding  ai/monsters/poltergeist to xrGame
adding  ai/monsters/pseudodog to xrGame
adding  ai/monsters/pseudogigant to xrGame
adding  ai/monsters/rats to xrGame
adding  ai/monsters/snork to xrGame
adding  ai/monsters/states to xrGame
adding  ai/monsters/tushkano to xrGame
adding  ai/monsters/zombie to xrGame
adding  ai/phantom to xrGame
adding  ai/stalker to xrGame
adding  ai/trader to xrGame
adding  CdkeyDecode to xrGame
adding  ik to xrGame
adding  ui to xrGame
adding  gamespy to xrGame
adding  ../xrServerEntities to xrGame
-- C CXX target xrGame cotired.
adding  . to xrGameSpy
-- CXX target xrGameSpy cotired.
adding  . to xrNetServer
adding  empty to xrNetServer
-- CXX target xrNetServer cotired.
adding  . to xrParticles
-- CXX target xrParticles cotired.
adding  . to xrPhysics
adding  tri-colliderknoopc to xrPhysics
adding  dcylinder to xrPhysics
-- CXX target xrPhysics cotired.
adding  . to xrScriptEngine
adding  LuaStudio to xrScriptEngine
-- CXX target xrScriptEngine cotired.
adding  . to xrSound
-- CXX target xrSound cotired.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/lonesimba/Desktop/stalker/xray-16/bin
$ make -j2
Scanning dependencies of target minilua
Scanning dependencies of target cximage
[  1%] Building C object Externals/CMakeFiles/minilua.dir/LuaJIT/src/host/minilua.c.o
[  2%] Building CXX object Externals/cximage/CMakeFiles/cximage.dir/ximacfg.cpp.o
clang: warning: -Wl,--no-undefined: 'linker' input unused [-Wunused-command-line-argument]
In file included from /home/lonesimba/Desktop/stalker/xray-16/Externals/cximage/ximacfg.cpp:1:
In file included from /home/lonesimba/Desktop/stalker/xray-16/Externals/cximage/ximacfg.h:7:
In file included from /home/lonesimba/Desktop/stalker/xray-16/Externals/cximage/../../src/Common/Common.hpp:4:
In file included from /home/lonesimba/Desktop/stalker/xray-16/Externals/cximage/../../src/Common/Platform.hpp:22:
/home/lonesimba/Desktop/stalker/xray-16/Externals/cximage/../../src/Common/PlatformLinux.inl:88:9: error: 
      void function '_splitpath' should not return a value [-Wreturn-type]
        return EINVAL;
        ^      ~~~~~~
1 error generated.
Externals/cximage/CMakeFiles/cximage.dir/build.make:62: recipe for target 'Externals/cximage/CMakeFiles/cximage.dir/ximacfg.cpp.o' failed
make[2]: *** [Externals/cximage/CMakeFiles/cximage.dir/ximacfg.cpp.o] Error 1
CMakeFiles/Makefile2:305: recipe for target 'Externals/cximage/CMakeFiles/cximage.dir/all' failed
make[1]: *** [Externals/cximage/CMakeFiles/cximage.dir/all] Error 2
make[1]: *** Ожидание завершения заданий…
[  2%] Linking C executable minilua
[  2%] Built target minilua
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

### LINKED ISSUE #499: Broken compilation with LLVM 8.0.1
**Describe the bug**
I can't compile with LLVM 8.0.1:
/wrkdirs/usr/ports/games/openxray/work/xray-16-510/Externals/ode/ode/src/quickstep.cpp:428:9: error: no member named 'random_shuffle' in namespace 'std'
                        std::random_shuffle     (order,order+m);
                        ~~~~~^                                                                            
1 error generated.  

Note that std::random_shuffle was removed in C++17, but OpenXRay uses C++17. Either downgrade to C++14 or stop using std::random_shuffle.

**To Reproduce**
Try to compile with LLVM 8.0.1.

**Expected behavior**
The software should compile successfully.

**Desktop (please complete the following information):**
 - OS: FreeBSD 12.1-RC2
 - OpenXRay build version 510

### PR DESCRIPTION
**Pull request by q4a**
Some time ago clang compilation was broken, so I fixed it.
Travis: added to 4 clang related configs (clang-6/clang-7 on x64  with Release/Debug target).
Travis: commented out 2 configs: gcc-7 Debug target on x64/x86 - it was building more 50 mins and was always terminated by travis. Debug target building with clang now and we will know if somebody will broke it.

### CODE REVIEW

File: src/xrAICore/Components/problem_solver.h [hunk 1]
```diff
@@ -151,4 +151,4 @@ class CProblemSolver
     virtual void clear();
 };
 
-#include "xrAICore/Components/problem_solver_inline.h"
+//#include "xrAICore/Components/problem_solver_inline.h"
```
Comment (FreeZoneMods) [inline src/xrAICore/Components/problem_solver.h]: Are you sure?

File: src/xrGame/ai/monsters/state.cpp [hunk 2]
```diff
@@ -1,4 +1,17 @@
 #include "StdAfx.h"
+
+#ifdef DEBUG
+namespace debug
+{
+class text_tree;
+}
+
+class CBaseMonster
```
Comment (FreeZoneMods) [inline src/xrGame/ai/monsters/state.cpp:9]: Why only for debug mode?

File: src/xrGame/game_cl_mp.cpp [hunk 3]
```diff
@@ -1535,7 +1535,8 @@ void game_cl_mp::generate_file_name(string_path& file_name, LPCSTR file_suffix,
 #else
 void game_cl_mp::generate_file_name(string_path& file_name, LPCSTR file_suffix, time_t& date_time)
 {
-    xr_sprintf(file_name, "%s_%s", ctime(date_time), file_suffix);
+    std::time_t std_date_time = date_time;
```
Comment (FreeZoneMods) [inline src/xrGame/game_cl_mp.cpp]: Why do you need this temporary variable?

File: src/xrAICore/Components/problem_solver.h (hunk 1 above)
Comment (q4a) [reply src/xrAICore/Components/problem_solver.h]: Yes. Check full commit - I moved it:
https://github.com/q4a/xray-16/commit/710cd10d41620c7b0047d4eb4ad3b03c0b68c68e

Comment (FreeZoneMods) [reply src/xrAICore/Components/problem_solver.h]: The problem is the headers with the '_inline' suffix in the name are usually included to the headers without the suffix (and only to this headers). Moving the include could mislead somebody.

Comment (q4a) [reply src/xrAICore/Components/problem_solver.h]: We got some problems, when moved xrAICore from xrGame. One of them here - problem_solver_inline.h does not know about "ai()":
https://travis-ci.org/q4a/xray-16/jobs/462642365#L1952
When I added
#include "xrGame/ai_space.h"
I got another error:
xrAICore/Components/problem_solver_inline.h:367:36: error: member access into incomplete type 'CGraphEngine'
    m_failed = !ai().graph_engine().search(*this, reverse_search ? target_state() : current_state(),
                                                      ^
/home/1/code/xray-16/src/xrAICore/../xrAICore/AISpaceBase.hpp:8:7: note: forward declaration of 'CGraphEngine'

So CGraphEngine is main problem: it includes "xrAICore/Components/problem_solver.h" (L23) before adding template for "search"  (L104): 
https://github.com/OpenXRay/xray-16/blob/b4f778f72e1db6ef138094bd0a28685faacc316b/src/xrAICore/Navigation/graph_engine.h#L23

File: src/xrGame/ai/monsters/state.cpp (hunk 2 above)
Comment (q4a) [reply src/xrGame/ai/monsters/state.cpp:9]: Because problem was only in debug mode ( here is travis build status before this fix: https://travis-ci.org/q4a/xray-16/builds/463837730 ).
And it's based on "base_monster.h". It's only for debug mode in base_monster.h too:
https://github.com/OpenXRay/xray-16/blob/686f5db0b70cdbfb9f28786fc7d4e0e145b53085/src/xrGame/ai/monsters/basemonster/base_monster.h#L45

File: src/xrGame/game_cl_mp.cpp (hunk 3 above)
Comment (q4a) [reply src/xrGame/game_cl_mp.cpp]: If I write "ctime(&(std::time_t)date_time)" - I'll get error:
src/xrGame/game_cl_mp.cpp:1539:42: error: cannot take the
      address of an rvalue of type 'std::time_t' (aka 'long')
    xr_sprintf(file_name, "%s_%s", ctime(&(std::time_t)std_date_time)...
So I based on this answers:
https://stackoverflow.com/questions/36576285/convert-long-int-to-const-time-t

Comment (FreeZoneMods) [reply src/xrGame/game_cl_mp.cpp]: But the date_time variable is a reference to a type 'time_t' (I suggest you to mark is additionaly as const). So does it mean that 'std::time_t' and 'time_t' are different types here?

File: src/xrAICore/Components/problem_solver.h (hunk 1 above)
Comment (q4a) [reply src/xrAICore/Components/problem_solver.h]: @FreeZoneMods we should check this commit:
https://github.com/Zegeri/xray-16/commit/578e9423c132740b09f4381700adeaff9087b9c3
may be it will help to aviod removing problem_solver_inline.h  from problem_solver.h

File: src/xrGame/game_cl_mp.cpp (hunk 3 above)
Comment (q4a) [reply src/xrGame/game_cl_mp.cpp]: Yes, different types here.
https://travis-ci.org/OpenXRay/xray-16/jobs/468604698#L3347 - gcc warning says "invalid conversion from ‘time_t {aka long int}’ to ‘const time_t* {aka const long int*}’ [-fpermissive]"

Comment (FreeZoneMods) [reply src/xrGame/game_cl_mp.cpp]: The types are not so different, but the solution looks ugly. And ifdef's, of course... I reimplement the function in PR #301, please check if the warning disappear.

File: src/xrAICore/Components/problem_solver.h (hunk 1 above)
Comment (FreeZoneMods) [reply src/xrAICore/Components/problem_solver.h]: Maybe we should find a way to remove ai() call from this problem solver at all? Calling ai() itself seems strange here.
And seems like it's just a warning, not an error.

Comment (q4a) [reply src/xrAICore/Components/problem_solver.h]: I'll think about removing ai() from here, but I'm already checked Zegeri's commit: 
https://github.com/Zegeri/xray-16/commit/578e9423c132740b09f4381700adeaff9087b9c3
He fixed problem of ai(), but not fixed access into incomplete type 'CGraphEngine' - here is clang build log:
https://travis-ci.org/q4a/xray-16/jobs/469356988#L7898

**Comment by Saiv46** [comment]
Any news?
