### ISSUE TITLE
Linux build error

### ISSUE THREAD

**Issue by xrombik** [OpenXRay/xray-16#325]
Build on Linux Mint 19.1 produces the following error:
```
/xray-16/src/utils/xrQSlim/../../xrCore/Memory/xalloc.h:3:10: fatal error: xrMemory.h: No such file or directory
 #include "xrMemory.h"
          ^~~~~~~~~~~~
```

**Comment by uralets** [comment]
f372e3e fixes this
