### PR TITLE
Fixed xrAICore compilation with LLVM on linux

### LINKED ISSUE #289: [Linux] Clang build issues
Fatal error while building at Linux Ubuntu 18.04
CLang ver 6.0 used
There's console output:
$ CC=clang-6.0 CXX=clang++-6.0 CFLAGS="-march=native" CXXFLAGS="-march=native" cmake ..
-- The C compiler identification is Clang 6.0.0
-- The CXX compiler identification is Clang 6.0.0
-- Check for working C compiler: /usr/bin/clang-6.0
-- Check for working C compiler: /usr/bin/clang-6.0 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/clang++-6.0
-- Check for working CXX compiler: /usr/bin/clang++-6.0 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- cotire 1.8.0 loaded.
CMake build Release, CFLAGS=-march=native, CXXFLAGS=-march=native -fpermissive --std=c++17 -Wno-attributes -pipe -Wl,--no-undefined -fvisibility=hidden
-- Found GLEW: /usr/include  
-- Found FreeImage: /usr/include, /usr/lib/x86_64-linux-gnu/libfreeimage.so
-- Found LockFile: /usr/include, /usr/lib/x86_64-linux-gnu/liblockfile.so
-- Found OpenAL: /usr/lib/x86_64-linux-gnu/libopenal.so  
-- Found Crypto++: /usr/include/crypto++, /usr/lib/x86_64-linux-gnu/libcryptopp.so
-- Found PugiXML: /usr/lib/x86_64-linux-gnu/libpugixml.so  
-- PugiXML include = /usr/include
-- PugiXML library = /usr/lib/x86_64-linux-gnu/libpugixml.so
-- theora found: includes in /usr/include, library in /usr/lib/x86_64-linux-gnu/libtheora.so;/usr/lib/x86_64-linux-gnu/libogg.so;/usr/lib/x86_64-linux-gnu/libvorbis.so
-- Found Ogg: /usr/lib/x86_64-linux-gnu/libogg.so  
-- Found SDL: /usr/lib/x86_64-linux-gnu/libSDL2.so (found version "2.0.8") 
-- Found LZO: /usr/lib/x86_64-linux-gnu/liblzo2.so  
-- Found JPEG: /usr/lib/x86_64-linux-gnu/libjpeg.so  
-- Found Intel TBB, includes /usr/include, /usr/lib/x86_64-linux-gnu/libtbb.so;/usr/lib/x86_64-linux-gnu/libtbbmalloc.so;/usr/lib/x86_64-linux-gnu/libtbbmalloc_proxy.so
-- The ASM compiler identification is Clang
-- Found assembler: /usr/bin/clang-6.0
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Found readline: /usr/lib/x86_64-linux-gnu/libreadline.so  
-- Found Curses: /usr/lib/x86_64-linux-gnu/libcurses.so  
DASM_FLAGS: -D FPU -D HFABI -D P64 -D JIT -D FFI -D SSE2 -D VER=
DASM_ARCH: x86
Build shared lib
adding  ./src/GameSpy to GameSpy
adding  ./src/GameSpy/common to GameSpy
adding  ./src/GameSpy/gcdkey to GameSpy
adding  ./src/GameSpy/ghttp to GameSpy
adding  ./src/GameSpy/GP to GameSpy
adding  ./src/GameSpy/gstats to GameSpy
adding  ./src/GameSpy/gt2 to GameSpy
adding  ./src/GameSpy/natneg to GameSpy
adding  ./src/GameSpy/pt to GameSpy
adding  ./src/GameSpy/qr2 to GameSpy
adding  ./src/GameSpy/sake to GameSpy
adding  ./src/GameSpy/sc to GameSpy
adding  ./src/GameSpy/serverbrowsing to GameSpy
adding  ./src/GameSpy/webservices to GameSpy
adding  . to OPCODE
adding  ode/src to ODE
adding  include/ode to ODE
adding  contrib/msvc7/ode_default to ODE
adding  . to xrLCUtil
-- CXX target xrLCUtil cotired.
adding  src to xrQSlim
adding  . to xrMiscMath
-- CXX target xrMiscMath cotired.
adding  . to xrRender_GL
adding  ../xrRender to xrRender_GL
adding  ../xrRender/blenders to xrRender_GL
adding  ../xrRenderGL to xrRender_GL
adding  ../xrRenderGL/MSAA to xrRender_GL
adding  ../xrRenderGL/GL Rain to xrRender_GL
adding  ../../Include/xrRender to xrRender_GL
-- CXX target xrRender_GL cotired.
adding  . to xr_3da
adding  . to xrAICore
adding  Components to xrAICore
adding  Navigation to xrAICore
adding  Navigation/PatrolPath to xrAICore
adding  Navigation/PathManagers to xrAICore
-- CXX target xrAICore cotired.
path /home/lonesimba/Desktop/stalker/xray-16/src/xrUICore
adding  . to xrCDB
-- CXX target xrCDB cotired.
adding  . to xrCore
adding  Animation to xrCore
adding  Compression to xrCore
adding  Containers to xrCore
adding  Crypto to xrCore
adding  Math to xrCore
adding  Media to xrCore
adding  PostProcess to xrCore
adding  Text to xrCore
adding  Threading to xrCore
adding  XML to xrCore
adding  ../xrCommon to xrCore
commit: cf1329d6759723a5840b58b00a7660ccb16b1f94
branch: xd_dev
-- CXX target xrCore cotired.
adding  . to xrEngine
adding  StringTable to xrEngine
-- CXX target xrEngine cotired.
adding  . to xrGame
adding  ai to xrGame
adding  ai/crow to xrGame
adding  ai/monsters to xrGame
adding  ai/monsters/basemonster to xrGame
adding  ai/monsters/bloodsucker to xrGame
adding  ai/monsters/boar to xrGame
adding  ai/monsters/burer to xrGame
adding  ai/monsters/cat to xrGame
adding  ai/monsters/chimera to xrGame
adding  ai/monsters/controller to xrGame
adding  ai/monsters/dog to xrGame
adding  ai/monsters/flesh to xrGame
adding  ai/monsters/fracture to xrGame
adding  ai/monsters/group_states to xrGame
adding  ai/monsters/poltergeist to xrGame
adding  ai/monsters/pseudodog to xrGame
adding  ai/monsters/pseudogigant to xrGame
adding  ai/monsters/rats to xrGame
adding  ai/monsters/snork to xrGame
adding  ai/monsters/states to xrGame
adding  ai/monsters/tushkano to xrGame
adding  ai/monsters/zombie to xrGame
adding  ai/phantom to xrGame
adding  ai/stalker to xrGame
adding  ai/trader to xrGame
adding  CdkeyDecode to xrGame
adding  ik to xrGame
adding  ui to xrGame
adding  gamespy to xrGame
adding  ../xrServerEntities to xrGame
-- C CXX target xrGame cotired.
adding  . to xrGameSpy
-- CXX target xrGameSpy cotired.
adding  . to xrNetServer
adding  empty to xrNetServer
-- CXX target xrNetServer cotired.
adding  . to xrParticles
-- CXX target xrParticles cotired.
adding  . to xrPhysics
adding  tri-colliderknoopc to xrPhysics
adding  dcylinder to xrPhysics
-- CXX target xrPhysics cotired.
adding  . to xrScriptEngine
adding  LuaStudio to xrScriptEngine
-- CXX target xrScriptEngine cotired.
adding  . to xrSound
-- CXX target xrSound cotired.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/lonesimba/Desktop/stalker/xray-16/bin
$ make -j2
Scanning dependencies of target minilua
Scanning dependencies of target cximage
[  1%] Building C object Externals/CMakeFiles/minilua.dir/LuaJIT/src/host/minilua.c.o
[  2%] Building CXX object Externals/cximage/CMakeFiles/cximage.dir/ximacfg.cpp.o
clang: warning: -Wl,--no-undefined: 'linker' input unused [-Wunused-command-line-argument]
In file included from /home/lonesimba/Desktop/stalker/xray-16/Externals/cximage/ximacfg.cpp:1:
In file included from /home/lonesimba/Desktop/stalker/xray-16/Externals/cximage/ximacfg.h:7:
In file included from /home/lonesimba/Desktop/stalker/xray-16/Externals/cximage/../../src/Common/Common.hpp:4:
In file included from /home/lonesimba/Desktop/stalker/xray-16/Externals/cximage/../../src/Common/Platform.hpp:22:
/home/lonesimba/Desktop/stalker/xray-16/Externals/cximage/../../src/Common/PlatformLinux.inl:88:9: error: 
      void function '_splitpath' should not return a value [-Wreturn-type]
        return EINVAL;
        ^      ~~~~~~
1 error generated.
Externals/cximage/CMakeFiles/cximage.dir/build.make:62: recipe for target 'Externals/cximage/CMakeFiles/cximage.dir/ximacfg.cpp.o' failed
make[2]: *** [Externals/cximage/CMakeFiles/cximage.dir/ximacfg.cpp.o] Error 1
CMakeFiles/Makefile2:305: recipe for target 'Externals/cximage/CMakeFiles/cximage.dir/all' failed
make[1]: *** [Externals/cximage/CMakeFiles/cximage.dir/all] Error 2
make[1]: *** Ожидание завершения заданий…
[  2%] Linking C executable minilua
[  2%] Built target minilua
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

### LINKED ISSUE #499: Broken compilation with LLVM 8.0.1
**Describe the bug**
I can't compile with LLVM 8.0.1:
/wrkdirs/usr/ports/games/openxray/work/xray-16-510/Externals/ode/ode/src/quickstep.cpp:428:9: error: no member named 'random_shuffle' in namespace 'std'
                        std::random_shuffle     (order,order+m);
                        ~~~~~^                                                                            
1 error generated.  

Note that std::random_shuffle was removed in C++17, but OpenXRay uses C++17. Either downgrade to C++14 or stop using std::random_shuffle.

**To Reproduce**
Try to compile with LLVM 8.0.1.

**Expected behavior**
The software should compile successfully.

**Desktop (please complete the following information):**
 - OS: FreeBSD 12.1-RC2
 - OpenXRay build version 510

### PR DESCRIPTION
**Pull request by astrdark**
Wip on removing inline.h

### CODE REVIEW

File: src/xrAICore/Navigation/graph_engine.h [hunk 1]
```diff
@@ -109,4 +109,6 @@ class CGraphEngine
 #endif
 };
 
+#include "xrAICore/Navigation/PathManagers/path_manager.h"
+#include "xrAICore/Components/problem_solver_inline.h"
```
Comment (FreeZoneMods) [inline src/xrAICore/Navigation/graph_engine.h:113]: It's not a good idea to remove 'inline' headers from 'base' headers with including 'inline's in different files. The trick with 'inline' headers is used in many places of the engine and your changes may mislead other people. Please try to find a better solution. 
P.S. The same changes were suggested in PR #299.

**Review by FreeZoneMods — CHANGES_REQUESTED** [review]

File: src/xrAICore/Navigation/graph_engine.h (hunk 1 above)
Comment (q4a) [reply src/xrAICore/Navigation/graph_engine.h:113]: And I don't remove 'inline' headers from 'base' headers with last commit:
https://github.com/OpenXRay/xray-16/pull/299/commits/70e5cd5274d8282bc863968c65873dc5f98540c9
